### ISSUE TITLE
contato

### ISSUE THREAD

**Issue by gabrielbiel7** [vhoyer/dotfiles#1]
ola, vinicius. sou do rio e queria saber como consigo conversar com você. vi que me ajudou com o problema da lista do popcorn time, mas ainda não consegui resposta dos administradores e moderadores e ainda fala português. Por favor, me deixe algum link para que eu possa conversar sobre este problema, o código que o outro moderador passou não ajudou. Obrigado e desculpa incomodar.

**Comment by vhoyer** [comment]
podes usar meu discord: vhoyer/harlog#6368 o problema maior, é que eu não respondi no #308 do popcorn pq não sei como te ajudar, se vc for ver, eu não contribuo para o desenvolvimento daquele programa.

**Comment by gabrielbiel7** [comment]
entendi. o chato é que aquele é um bug mto antigo e até hoje não houve solução. tentei o tal link do github do jimi c, funcionou e consegui entrar no ep que faltava pela lista mas não carregava, so pelos favoritos. vc tem alguma ideia ou testou alguma modificação no watchlist.js que deu certo?

**Comment by vhoyer** [comment]
to ligado do bug, tbm gostaria de ver ele funcionando, é que a parte que falta é justamente, achar o torrent pra reproduzir o video. não cheguei a testar a versão dele não, mas talvez eu faça isso hoje de tarde, não fique na esperança, não é como se eu fosse conseguir fazer nem nada kk

**Comment by gabrielbiel7** [comment]
kkkkk de boa, eu não entendo nada sobre isso de código e etc, só queria que resolvessem esse bug, mas se não conseguir, não tem problema. eu mesmo uso o tvshowtime para ver os eps novos, mas o site ta com uns problemas ultimamente e por enquanto ta off-line, ai a watchlist seria uma função interessante, se funcionasse.

**Comment by gabrielbiel7** [comment]
oi vinicius, desculpa por encher teu saco de novo kkk conseguiu resolver o problema na hora de achar o torrent?

**Comment by vhoyer** [comment]
ainda não man, tô tentando, mas o código é bem complicado e não tem quase documentação nenhuma, tô tentando descobrir como que ele funciona...

**Comment by vhoyer** [comment]
nao sei se voce viu, mas ja foi resolvido, neh? xD
