### ISSUE TITLE
Use zsh instead of bash

### ISSUE THREAD

**Issue by onlurking** [vhoyer/dotfiles#3]
Please, use zsh:
- [Why](https://www.slideshare.net/jaguardesignstudio/why-zsh-is-cooler-than-your-shell-16194692)

zsh ecosystem:
- [plugin manager](https://github.com/robbyrussell/oh-my-zsh)
- [syntax highlighting](https://github.com/zsh-users/zsh-syntax-highlighting)
- [typeahead Suggestions](https://github.com/zsh-users/zsh-autosuggestions)
- [otherplugins](https://github.com/unixorn/awesome-zsh-plugins)

prompt theme suggestion:
- [lambda mod](https://github.com/halfo/lambda-mod-zsh-theme)
- [spaceship prompt](https://github.com/denysdovhan/spaceship-prompt)

**Comment by vhoyer** [comment]
done
